---
apiVersion: v1
data:
  handler.json: |
    {
      "handlers": {
        "default": {
          "command": null,
          "type": "set",
          "filters": [

          ],
          "severities": [
            "ok",
            "warning",
            "critical",
            "unknown"
          ],
          "handlers": [
          ]
        }
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: sensu-handlers
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sensu
    component: server
  name: sensu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensu
      component: server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensu
        component: server
    spec:
      volumes:
        - name: sensu-config
          configMap:
            name: sensu-config
        - name: sensu-handlers
          configMap:
            name: sensu-handlers
      containers:
      - args:
        - server
        image: jaxxstorm/sensu:v1.2
        imagePullPolicy: Always
        env:
          - name: NO_CONFIGURE_DEFAULTS
            value: "true"
          - name: LOG_LEVEL
            value: "debug"
        name: sensu-server
        resources: {}
        volumeMounts:
          - name: sensu-config
            mountPath: /etc/sensu/conf.d
          - name: sensu-handlers
            mountPath: /etc/sensu/handlers
status: {}
