---
apiVersion: v1
data:
  config.json: |
    {
      "sensu": [
        {
          "name": "GKE",
          "host": "sensu-api",
          "port": 4567
        }
      ],
      "uchiwa": {
        "host": "0.0.0.0",
        "port": 3000,
        "users": [
          {
          "username": "admin",
          "password": "{crypt}$apr1$nspYCiwq$7Ef8uKpRqjdYmOFMghnAa."
          }
        ]
      }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: uchiwa-config
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/allow-http: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: uchiwa-ingress
spec:
  tls:
  - hosts:
    - uchiwa.lbrlabs.com
    secretName: uchiwa-tls
  rules:
  - host: uchiwa.lbrlabs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: uchiwa
          servicePort: 3000
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sensu
    component: uchiwa
  name: uchiwa
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: sensu
    component: uchiwa
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sensu
    component: uchiwa
  name: uchiwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensu
      component: uchiwa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sensu
        component: uchiwa
    spec:
      volumes:
        - name: uchiwa-config
          configMap:
            name: uchiwa-config
      containers:
      - args:
        - -c
        - /etc/uchiwa/config.json
        - -d
        - /etc/uchiwa/config.d
        command: 
        - /go/bin/uchiwa
        image: uchiwa/uchiwa:1.3.1-1
        ports:
          - containerPort: 3000
        name: sensu-api
        resources: {}
        volumeMounts:
          - name: uchiwa-config
            mountPath: /etc/uchiwa
status: {}
